### ISSUE TITLE
Splitting two words joined by ellipsis (...) and no spaces into different tokens

### ISSUE THREAD

**Issue by swaroopgrs** [fnl/syntok#1]
Example:
For the sentence `Lalala...or Lala Land....`, currently the first output token is `Lalala...or`. Would it make sense to split this into multiple tokens?

**Comment by fnl** [comment]
Totally agree, this should be spit into three tokens, `Lalala`, `...` and `or`.

**Comment by fnl** [comment]
Released version 1.1.0, that now properly splits tokens with inner ellipses and treats ellipses as proper tokens.
