### ISSUE TITLE
Uppercase letters in tokens

### ISSUE THREAD

**Issue by severinsimmler** [fnl/syntok#10]
Is it intended that capital letters are split into two tokens even if it is an IMHO semantic unit, such as `GmbH`, which is tokenized as `Gmb` and `H`?

```python
>>> from syntok.tokenizer import Tokenizer
>>> tok = Tokenizer()
>>> document = "GmbH"
>>> for token in tok.tokenize(document):
...     print(repr(token))
... 
<Token '' : 'Gmb' @ 0>
<Token '' : 'H' @ 3>
```

**Comment by severinsimmler** [comment]
I know you write in the README:

> The Tokenizer considers camelCase words as individual tokens (here: camel and Case) and by default considers underscores and Unicode hyphens inside words as spacing characters (not Token values).

But when does this make sense?

**Comment by fnl** [comment]
Good question!

This is most useful for normalizing proper names that can be joined using hyphens, white-spaces, or this camel-case form. Typical examples where this happens a lot are company and gene names, but also in other business domains.

By uniformly tokenizing these three spelling variants you can then use that tokenized base form in your look-ups of your Named Entity Linking system, for example.

**Comment by fnl** [comment]
Let me know if that clears things up and I can close this issue or if you still have open thoughts.

**Comment by severinsimmler** [comment]
Thanks for the quick answer. And yes, from this point of view this decision makes perfect sense.
