### ISSUE TITLE
Missed abbreviations (Min., Sen.)

### ISSUE THREAD

**Issue by peter-lang-dealogic** [fnl/syntok#26]
Example texts:
- Warren: $20,000 in College Debt 'Might As Well Be $20 Million' for Min. Wage Workers
- Sen. Elizabeth Warren called on Biden to cancel student debt after he extended the payment pause again.
- A number of high-ranking American officers at Kasserine were removed, including the commanding officer, Maj. Gen. Lloyd Fredendall, who was replaced by Maj. Gen. George Patton and sent home for more training.
- The case is Nath v. Lightspeed Commerce Inc., et al., 21-cv-06365910.

**Comment by fnl** [comment]
Resolved by v1.4.4, except for "Maj." which seems too uncommon ITBD).
