### ISSUE TITLE
There's no direct way of getting offset of a sentence w.r.t. a document.

### ISSUE THREAD

**Issue by ZeeshanA1i** [fnl/syntok#5]
Many existing sentence segmentors such as those of NLTK or SpaCy give a list of sentence objects after splitting a document. The advantage of which is that one can get other information of a sentence from that object.

```
import spacy 
nlp = spacy.load('en_core_web_md')
document = "The child who has a rash. I don't know who has a rash. The reason why is unknown."
for sentence in nlp(document).sents:
    print (type(sentence))
    print (sentence.text)
    print (sentence.start_char) # offset of the sentence w.r.t. the document
```

**Output:**

> <class 'spacy.tokens.span.Span'>
> The child who has a rash.
> 0
> <class 'spacy.tokens.span.Span'>
> I don't know who has a rash.
> 26
> <class 'spacy.tokens.span.Span'>
> The reason why is unknown.
> 55
> 

However, syntok just provides sentence as a list of tokens and therefore one can not directly get the offset of the sentence.

```
import syntok.segmenter as segmenter
document = "The child who has a rash. I don't know who has a rash. The reason why is unknown."

for paragraph in segmenter.analyze(document):
    for sentence in paragraph:
        print (type(sentence))
        for token in sentence:
            # exactly reproduce the input
            # and do not remove "imperfections"
            print(token.spacing, token.value, sep='', end='')
        print("\n")  # reinsert paragraph separators
    print("\n")  # reinsert paragraph separators
```

**Output:**

> <class 'list'>
> The child who has a rash.
> 
> <class 'list'>
>  I don't know who has a rash.
> 
> <class 'list'>
>  The reason why is unknown.
> 

It would be great if syntok follows the similar way of defining a sentence (ie as an object and not as a list or so) in upcoming versions.

**Comment by fnl** [comment]
Hi @ZeeshanA1i , first, thank you for your interest in syntok!

Here comes the good news for your suggestion:
syntok already supports _exactly_ what you are asking for!

syntok sentences are Python lists consisting of [Token](https://github.com/fnl/syntok/blob/5100e7bb1ae5c2b0f4c9bb9b06a8f41d8bc586c3/syntok/tokenizer.py#L6) objects.
And those tokens in turn store their absolute offset where they were found in the text.

Let me show you how you can get nearly the same output today with syntok as you show for SpaCy.
All you need to do is add the `Token.offset` property of the first token in a sentence to a print statement in your code example:

```python
for paragraph in segmenter.analyze(document):
        for sentence in paragraph:
            print(type(sentence))
            for token in sentence:
                # exactly reproduce the input
                # and do not remove "imperfections"
                print(token.spacing, token.value, sep='', end='')
            print("\n", sentence[0].offset, sep='')
```
(Note I also removed the last print statement to make the output _exactly_ equal to that of SpaCy.)

*Output:*

> <class 'list'>
> The child who has a rash.
> 0
> <class 'list'>
>  I don't know who has a rash.
> 26
> <class 'list'>
>  The reason why is unknown.
> 55

Which, except for the sentence type (list vs. Span) is exactly the same output as you show for SpaCy.
